language: python
python:
  - "3.5"

install:
  - python setup.py install
  #- pip install yaml
  
services:
  - xvfb
  
script:
  - xvfb-run make test
  - python vmarker.py  sample/data/samplevideo.avi 

